# pragma once

# include <unordered_map>
# include <string>


static const std::unordered_map<std::string, std::string> LANGUAGE_MAP = {
    {"aa","Afar"},
    {"ab","Abkhazian"},
    {"ace","Acehnese"},
    {"ach","Acoli"},
    {"ada","Adangme"},
    {"ady","Adyghe"},
    {"ae","Avestan"},
    {"aeb","Tunisian Arabic"},
    {"af","Afrikaans"},
    {"afh","Afrihili"},
    {"agq","Aghem"},
    {"ain","Ainu"},
    {"ak","Akan"},
    {"akk","Akkadian"},
    {"akz","Alabama"},
    {"ale","Aleut"},
    {"aln","Gheg Albanian"},
    {"alt","Southern Altai"},
    {"am","Amharic"},
    {"an","Aragonese"},
    {"ang","Old English"},
    {"ann","Obolo"},
    {"anp","Angika"},
    {"ar","Arabic"},
    {"ar-001","Modern Standard Arabic"},
    {"arc","Aramaic"},
    {"arn","Mapuche"},
    {"aro","Araona"},
    {"arp","Arapaho"},
    {"arq","Algerian Arabic"},
    {"ars","Najdi Arabic"},
    {"ars-alt-menu","Arabic, Najdi"},
    {"arw","Arawak"},
    {"ary","Moroccan Arabic"},
    {"arz","Egyptian Arabic"},
    {"as","Assamese"},
    {"asa","Asu"},
    {"ase","American Sign Language"},
    {"ast","Asturian"},
    {"atj","Atikamekw"},
    {"av","Avaric"},
    {"avk","Kotava"},
    {"awa","Awadhi"},
    {"ay","Aymara"},
    {"az","Azerbaijani"},
    {"az-alt-short","Azeri"},
    {"ba","Bashkir"},
    {"bal","Baluchi"},
    {"ban","Balinese"},
    {"bar","Bavarian"},
    {"bas","Basaa"},
    {"bax","Bamun"},
    {"bbc","Batak Toba"},
    {"bbj","Ghomala"},
    {"be","Belarusian"},
    {"bej","Beja"},
    {"bem","Bemba"},
    {"bew","Betawi"},
    {"bez","Bena"},
    {"bfd","Bafut"},
    {"bfq","Badaga"},
    {"bg","Bulgarian"},
    {"bgc","Haryanvi"},
    {"bgn","Western Balochi"},
    {"bho","Bhojpuri"},
    {"bi","Bislama"},
    {"bik","Bikol"},
    {"bin","Bini"},
    {"bjn","Banjar"},
    {"bkm","Kom"},
    {"bla","Siksiká"},
    {"blo","Anii"},
    {"blt","Tai Dam"},
    {"bm","Bambara"},
    {"bn","Bangla"},
    {"bo","Tibetan"},
    {"bpy","Bishnupriya"},
    {"bqi","Bakhtiari"},
    {"bqi-alt-variant","Luri Bakhtiari"},
    {"br","Breton"},
    {"bra","Braj"},
    {"brh","Brahui"},
    {"brx","Bodo"},
    {"bs","Bosnian"},
    {"bss","Akoose"},
    {"bua","Buriat"},
    {"bug","Buginese"},
    {"bum","Bulu"},
    {"byn","Blin"},
    {"byv","Medumba"},
    {"ca","Catalan"},
    {"cad","Caddo"},
    {"car","Carib"},
    {"cay","Cayuga"},
    {"cch","Atsam"},
    {"ccp","Chakma"},
    {"ce","Chechen"},
    {"ceb","Cebuano"},
    {"cgg","Chiga"},
    {"ch","Chamorro"},
    {"chb","Chibcha"},
    {"chg","Chagatai"},
    {"chk","Chuukese"},
    {"chm","Mari"},
    {"chn","Chinook Jargon"},
    {"cho","Choctaw"},
    {"chp","Chipewyan"},
    {"chr","Cherokee"},
    {"chy","Cheyenne"},
    {"cic","Chickasaw"},
    {"ckb","Central Kurdish"},
    {"ckb-alt-menu","Kurdish, Central"},
    {"ckb-alt-variant","Kurdish, Sorani"},
    {"ckb-menu-core","Kurdish"},
    {"ckb-menu-extension","Central"},
    {"clc","Chilcotin"},
    {"co","Corsican"},
    {"cop","Coptic"},
    {"cps","Capiznon"},
    {"cr","Cree"},
    {"cr-alt-long","Woods Cree"},
    {"crg","Michif"},
    {"crh","Crimean Tatar"},
    {"crj","Southern East Cree"},
    {"crk","Plains Cree"},
    {"crl","Northern East Cree"},
    {"crm","Moose Cree"},
    {"crr","Carolina Algonquian"},
    {"crs","Seselwa Creole French"},
    {"cs","Czech"},
    {"csb","Kashubian"},
    {"csw","Swampy Cree"},
    {"cu","Church Slavic"},
    {"cv","Chuvash"},
    {"cy","Welsh"},
    {"da","Danish"},
    {"dak","Dakota"},
    {"dar","Dargwa"},
    {"dav","Taita"},
    {"de","German"},
    {"de-AT","Austrian German"},
    {"de-CH","Swiss High German"},
    {"del","Delaware"},
    {"den","Slave"},
    {"dgr","Dogrib"},
    {"din","Dinka"},
    {"dje","Zarma"},
    {"doi","Dogri"},
    {"dsb","Lower Sorbian"},
    {"dtp","Central Dusun"},
    {"dua","Duala"},
    {"dum","Middle Dutch"},
    {"dv","Divehi"},
    {"dyo","Jola-Fonyi"},
    {"dyu","Dyula"},
    {"dz","Dzongkha"},
    {"dzg","Dazaga"},
    {"ebu","Embu"},
    {"ee","Ewe"},
    {"efi","Efik"},
    {"egl","Emilian"},
    {"egy","Ancient Egyptian"},
    {"eka","Ekajuk"},
    {"el","Greek"},
    {"elx","Elamite"},
    {"en","English"},
    {"en-AU","Australian English"},
    {"en-CA","Canadian English"},
    {"en-GB","British English"},
    {"en-GB-alt-short","UK English"},
    {"en-US","American English"},
    {"en-US-alt-short","US English"},
    {"enm","Middle English"},
    {"eo","Esperanto"},
    {"es","Spanish"},
    {"es-419","Latin American Spanish"},
    {"es-ES","European Spanish"},
    {"es-MX","Mexican Spanish"},
    {"esu","Central Yupik"},
    {"et","Estonian"},
    {"eu","Basque"},
    {"ewo","Ewondo"},
    {"ext","Extremaduran"},
    {"fa","Persian"},
    {"fa-AF","Dari"},
    {"fan","Fang"},
    {"fat","Fanti"},
    {"ff","Fula"},
    {"fi","Finnish"},
    {"fil","Filipino"},
    {"fit","Tornedalen Finnish"},
    {"fj","Fijian"},
    {"fo","Faroese"},
    {"fon","Fon"},
    {"fr","French"},
    {"fr-CA","Canadian French"},
    {"fr-CH","Swiss French"},
    {"frc","Cajun French"},
    {"frm","Middle French"},
    {"fro","Old French"},
    {"frp","Arpitan"},
    {"frr","Northern Frisian"},
    {"frs","Eastern Frisian"},
    {"fur","Friulian"},
    {"fy","Western Frisian"},
    {"ga","Irish"},
    {"gaa","Ga"},
    {"gag","Gagauz"},
    {"gan","Gan Chinese"},
    {"gay","Gayo"},
    {"gba","Gbaya"},
    {"gbz","Zoroastrian Dari"},
    {"gd","Scottish Gaelic"},
    {"gez","Geez"},
    {"gil","Gilbertese"},
    {"gl","Galician"},
    {"glk","Gilaki"},
    {"gmh","Middle High German"},
    {"gn","Guarani"},
    {"goh","Old High German"},
    {"gon","Gondi"},
    {"gor","Gorontalo"},
    {"got","Gothic"},
    {"grb","Grebo"},
    {"grc","Ancient Greek"},
    {"gsw","Swiss German"},
    {"gu","Gujarati"},
    {"guc","Wayuu"},
    {"gur","Frafra"},
    {"guz","Gusii"},
    {"gv","Manx"},
    {"gwi","Gwichʼin"},
    {"ha","Hausa"},
    {"hai","Haida"},
    {"hak","Hakka Chinese"},
    {"haw","Hawaiian"},
    {"hax","Southern Haida"},
    {"he","Hebrew"},
    {"hi","Hindi"},
    {"hi-Latn","Hindi (Latin)"},
    {"hi-Latn-alt-variant","Hinglish"},
    {"hif","Fiji Hindi"},
    {"hil","Hiligaynon"},
    {"hit","Hittite"},
    {"hmn","Hmong"},
    {"hnj","Hmong Njua"},
    {"ho","Hiri Motu"},
    {"hr","Croatian"},
    {"hsb","Upper Sorbian"},
    {"hsn","Xiang Chinese"},
    {"ht","Haitian Creole"},
    {"hu","Hungarian"},
    {"hup","Hupa"},
    {"hur","Halkomelem"},
    {"hy","Armenian"},
    {"hz","Herero"},
    {"ia","Interlingua"},
    {"iba","Iban"},
    {"ibb","Ibibio"},
    {"id","Indonesian"},
    {"ie","Interlingue"},
    {"ig","Igbo"},
    {"ii","Sichuan Yi"},
    {"ik","Inupiaq"},
    {"ikt","Western Canadian Inuktitut"},
    {"ilo","Iloko"},
    {"inh","Ingush"},
    {"io","Ido"},
    {"is","Icelandic"},
    {"it","Italian"},
    {"iu","Inuktitut"},
    {"izh","Ingrian"},
    {"ja","Japanese"},
    {"jam","Jamaican Creole English"},
    {"jbo","Lojban"},
    {"jgo","Ngomba"},
    {"jmc","Machame"},
    {"jpr","Judeo-Persian"},
    {"jrb","Judeo-Arabic"},
    {"jut","Jutish"},
    {"jv","Javanese"},
    {"ka","Georgian"},
    {"kaa","Kara-Kalpak"},
    {"kab","Kabyle"},
    {"kac","Kachin"},
    {"kaj","Jju"},
    {"kam","Kamba"},
    {"kaw","Kawi"},
    {"kbd","Kabardian"},
    {"kbl","Kanembu"},
    {"kcg","Tyap"},
    {"kde","Makonde"},
    {"kea","Kabuverdianu"},
    {"kek","Qʼeqchiʼ"},
    {"ken","Kenyang"},
    {"kfo","Koro"},
    {"kg","Kongo"},
    {"kgp","Kaingang"},
    {"kha","Khasi"},
    {"kho","Khotanese"},
    {"khq","Koyra Chiini"},
    {"khw","Khowar"},
    {"ki","Kikuyu"},
    {"kiu","Kirmanjki"},
    {"kj","Kuanyama"},
    {"kk","Kazakh"},
    {"kkj","Kako"},
    {"kl","Kalaallisut"},
    {"kln","Kalenjin"},
    {"km","Khmer"},
    {"kmb","Kimbundu"},
    {"kn","Kannada"},
    {"ko","Korean"},
    {"koi","Komi-Permyak"},
    {"kok","Konkani"},
    {"kos","Kosraean"},
    {"kpe","Kpelle"},
    {"kr","Kanuri"},
    {"krc","Karachay-Balkar"},
    {"kri","Krio"},
    {"krj","Kinaray-a"},
    {"krl","Karelian"},
    {"kru","Kurukh"},
    {"ks","Kashmiri"},
    {"ksb","Shambala"},
    {"ksf","Bafia"},
    {"ksh","Colognian"},
    {"ku","Kurdish"},
    {"ku-menu-core","Kurdish"},
    {"ku-menu-extension","Kurmanji"},
    {"kum","Kumyk"},
    {"kut","Kutenai"},
    {"kv","Komi"},
    {"kw","Cornish"},
    {"kwk","Kwakʼwala"},
    {"kxv","Kuvi"},
    {"ky","Kyrgyz"},
    {"ky-alt-variant","Kirghiz"},
    {"la","Latin"},
    {"lad","Ladino"},
    {"lag","Langi"},
    {"lah","Western Panjabi"},
    {"lam","Lamba"},
    {"lb","Luxembourgish"},
    {"lez","Lezghian"},
    {"lfn","Lingua Franca Nova"},
    {"lg","Ganda"},
    {"li","Limburgish"},
    {"lij","Ligurian"},
    {"lil","Lillooet"},
    {"liv","Livonian"},
    {"lkt","Lakota"},
    {"lmo","Lombard"},
    {"ln","Lingala"},
    {"lo","Lao"},
    {"lol","Mongo"},
    {"lou","Louisiana Creole"},
    {"loz","Lozi"},
    {"lrc","Northern Luri"},
    {"lsm","Saamia"},
    {"lt","Lithuanian"},
    {"ltg","Latgalian"},
    {"lu","Luba-Katanga"},
    {"lua","Luba-Lulua"},
    {"lui","Luiseno"},
    {"lun","Lunda"},
    {"luo","Luo"},
    {"lus","Mizo"},
    {"luy","Luyia"},
    {"lv","Latvian"},
    {"lzh","Literary Chinese"},
    {"lzz","Laz"},
    {"mad","Madurese"},
    {"maf","Mafa"},
    {"mag","Magahi"},
    {"mai","Maithili"},
    {"mak","Makasar"},
    {"man","Mandingo"},
    {"mas","Masai"},
    {"mde","Maba"},
    {"mdf","Moksha"},
    {"mdr","Mandar"},
    {"men","Mende"},
    {"mer","Meru"},
    {"mfe","Morisyen"},
    {"mg","Malagasy"},
    {"mga","Middle Irish"},
    {"mgh","Makhuwa-Meetto"},
    {"mgo","Metaʼ"},
    {"mh","Marshallese"},
    {"mi","Māori"},
    {"mic","Mi'kmaw"},
    {"min","Minangkabau"},
    {"mk","Macedonian"},
    {"ml","Malayalam"},
    {"mn","Mongolian"},
    {"mnc","Manchu"},
    {"mni","Manipuri"},
    {"moe","Innu-aimun"},
    {"moh","Mohawk"},
    {"mos","Mossi"},
    {"mr","Marathi"},
    {"mrj","Western Mari"},
    {"ms","Malay"},
    {"mt","Maltese"},
    {"mua","Mundang"},
    {"mul","Multiple languages"},
    {"mus","Muscogee"},
    {"mus-alt-official","Mvskoke"},
    {"mwl","Mirandese"},
    {"mwr","Marwari"},
    {"mwv","Mentawai"},
    {"my","Burmese"},
    {"my-alt-variant","Myanmar Language"},
    {"mye","Myene"},
    {"myv","Erzya"},
    {"mzn","Mazanderani"},
    {"na","Nauru"},
    {"nan","Min Nan Chinese"},
    {"nap","Neapolitan"},
    {"naq","Nama"},
    {"nb","Norwegian Bokmål"},
    {"nd","North Ndebele"},
    {"nds","Low German"},
    {"nds-NL","Low Saxon"},
    {"ne","Nepali"},
    {"new","Newari"},
    {"ng","Ndonga"},
    {"nia","Nias"},
    {"niu","Niuean"},
    {"njo","Ao Naga"},
    {"nl","Dutch"},
    {"nl-BE","Flemish"},
    {"nmg","Kwasio"},
    {"nn","Norwegian Nynorsk"},
    {"nnh","Ngiemboon"},
    {"no","Norwegian"},
    {"nog","Nogai"},
    {"non","Old Norse"},
    {"nov","Novial"},
    {"nqo","N’Ko"},
    {"nr","South Ndebele"},
    {"nso","Northern Sotho"},
    {"nus","Nuer"},
    {"nv","Navajo"},
    {"nwc","Classical Newari"},
    {"ny","Nyanja"},
    {"nym","Nyamwezi"},
    {"nyn","Nyankole"},
    {"nyo","Nyoro"},
    {"nzi","Nzima"},
    {"oc","Occitan"},
    {"oj","Ojibwa"},
    {"ojb","Northwestern Ojibwa"},
    {"ojc","Central Ojibwa"},
    {"ojs","Oji-Cree"},
    {"ojw","Western Ojibwa"},
    {"oka","Okanagan"},
    {"oka-alt-variant","Colville Salish"},
    {"om","Oromo"},
    {"or","Odia"},
    {"os","Ossetic"},
    {"osa","Osage"},
    {"ota","Ottoman Turkish"},
    {"pa","Punjabi"},
    {"pag","Pangasinan"},
    {"pal","Pahlavi"},
    {"pam","Pampanga"},
    {"pap","Papiamento"},
    {"pau","Palauan"},
    {"pcd","Picard"},
    {"pcm","Nigerian Pidgin"},
    {"pdc","Pennsylvania German"},
    {"pdt","Plautdietsch"},
    {"peo","Old Persian"},
    {"pfl","Palatine German"},
    {"phn","Phoenician"},
    {"pi","Pali"},
    {"pi-alt-variant","Pāli"},
    {"pis","Pijin"},
    {"pl","Polish"},
    {"pms","Piedmontese"},
    {"pnt","Pontic"},
    {"pon","Pohnpeian"},
    {"pqm","Maliseet-Passamaquoddy"},
    {"prg","Prussian"},
    {"pro","Old Provençal"},
    {"ps","Pashto"},
    {"ps-alt-variant","Pushto"},
    {"pt","Portuguese"},
    {"pt-BR","Brazilian Portuguese"},
    {"pt-PT","European Portuguese"},
    {"qu","Quechua"},
    {"quc","Kʼicheʼ"},
    {"qug","Chimborazo Highland Quichua"},
    {"raj","Rajasthani"},
    {"rap","Rapanui"},
    {"rar","Rarotongan"},
    {"rgn","Romagnol"},
    {"rhg","Rohingya"},
    {"rif","Riffian"},
    {"rm","Romansh"},
    {"rn","Rundi"},
    {"ro","Romanian"},
    {"ro-MD","Moldavian"},
    {"rof","Rombo"},
    {"rom","Romany"},
    {"rtm","Rotuman"},
    {"ru","Russian"},
    {"rue","Rusyn"},
    {"rug","Roviana"},
    {"rup","Aromanian"},
    {"rw","Kinyarwanda"},
    {"rwk","Rwa"},
    {"sa","Sanskrit"},
    {"sad","Sandawe"},
    {"sah","Yakut"},
    {"sam","Samaritan Aramaic"},
    {"saq","Samburu"},
    {"sas","Sasak"},
    {"sat","Santali"},
    {"saz","Saurashtra"},
    {"sba","Ngambay"},
    {"sbp","Sangu"},
    {"sc","Sardinian"},
    {"scn","Sicilian"},
    {"sco","Scots"},
    {"sd","Sindhi"},
    {"sdc","Sassarese Sardinian"},
    {"sdh","Southern Kurdish"},
    {"sdh-menu-core","Kurdish"},
    {"sdh-menu-extension","Southern"},
    {"se","Northern Sami"},
    {"se-alt-menu","Sami, Northern"},
    {"see","Seneca"},
    {"seh","Sena"},
    {"sei","Seri"},
    {"sel","Selkup"},
    {"ses","Koyraboro Senni"},
    {"sg","Sango"},
    {"sga","Old Irish"},
    {"sgs","Samogitian"},
    {"sh","Serbo-Croatian"},
    {"shi","Tachelhit"},
    {"shn","Shan"},
    {"shu","Chadian Arabic"},
    {"si","Sinhala"},
    {"sid","Sidamo"},
    {"sk","Slovak"},
    {"sl","Slovenian"},
    {"slh","Southern Lushootseed"},
    {"sli","Lower Silesian"},
    {"sly","Selayar"},
    {"sm","Samoan"},
    {"sma","Southern Sami"},
    {"sma-alt-menu","Sami, Southern"},
    {"smj","Lule Sami"},
    {"smj-alt-menu","Sami, Lule"},
    {"smn","Inari Sami"},
    {"smn-alt-menu","Sami, Inari"},
    {"sms","Skolt Sami"},
    {"sms-alt-menu","Sami, Skolt"},
    {"sn","Shona"},
    {"snk","Soninke"},
    {"so","Somali"},
    {"sog","Sogdien"},
    {"sq","Albanian"},
    {"sr","Serbian"},
    {"sr-ME","Montenegrin"},
    {"srn","Sranan Tongo"},
    {"srr","Serer"},
    {"ss","Swati"},
    {"ssy","Saho"},
    {"st","Southern Sotho"},
    {"stq","Saterland Frisian"},
    {"str","Straits Salish"},
    {"su","Sundanese"},
    {"suk","Sukuma"},
    {"sus","Susu"},
    {"sux","Sumerian"},
    {"sv","Swedish"},
    {"sw","Swahili"},
    {"sw-CD","Congo Swahili"},
    {"swb","Comorian"},
    {"syc","Classical Syriac"},
    {"syr","Syriac"},
    {"szl","Silesian"},
    {"ta","Tamil"},
    {"tce","Southern Tutchone"},
    {"tcy","Tulu"},
    {"te","Telugu"},
    {"tem","Timne"},
    {"teo","Teso"},
    {"ter","Tereno"},
    {"tet","Tetum"},
    {"tg","Tajik"},
    {"tgx","Tagish"},
    {"th","Thai"},
    {"tht","Tahltan"},
    {"ti","Tigrinya"},
    {"tig","Tigre"},
    {"tiv","Tiv"},
    {"tk","Turkmen"},
    {"tkl","Tokelauan"},
    {"tkr","Tsakhur"},
    {"tl","Tagalog"},
    {"tlh","Klingon"},
    {"tli","Tlingit"},
    {"tly","Talysh"},
    {"tmh","Tamashek"},
    {"tn","Tswana"},
    {"to","Tongan"},
    {"tog","Nyasa Tonga"},
    {"tok","Toki Pona"},
    {"tpi","Tok Pisin"},
    {"tr","Turkish"},
    {"tru","Turoyo"},
    {"trv","Taroko"},
    {"trw","Torwali"},
    {"ts","Tsonga"},
    {"tsd","Tsakonian"},
    {"tsi","Tsimshian"},
    {"tt","Tatar"},
    {"ttm","Northern Tutchone"},
    {"ttt","Muslim Tat"},
    {"tum","Tumbuka"},
    {"tvl","Tuvalu"},
    {"tw","Twi"},
    {"twq","Tasawaq"},
    {"ty","Tahitian"},
    {"tyv","Tuvinian"},
    {"tzm","Central Atlas Tamazight"},
    {"udm","Udmurt"},
    {"ug","Uyghur"},
    {"ug-alt-variant","Uighur"},
    {"uga","Ugaritic"},
    {"uk","Ukrainian"},
    {"umb","Umbundu"},
    {"und","Unknown language"},
    {"ur","Urdu"},
    {"uz","Uzbek"},
    {"vai","Vai"},
    {"ve","Venda"},
    {"vec","Venetian"},
    {"vep","Veps"},
    {"vi","Vietnamese"},
    {"vls","West Flemish"},
    {"vmf","Main-Franconian"},
    {"vmw","Makhuwa"},
    {"vo","Volapük"},
    {"vot","Votic"},
    {"vro","Võro"},
    {"vun","Vunjo"},
    {"wa","Walloon"},
    {"wae","Walser"},
    {"wal","Wolaytta"},
    {"war","Waray"},
    {"was","Washo"},
    {"wbp","Warlpiri"},
    {"wo","Wolof"},
    {"wuu","Wu Chinese"},
    {"xal","Kalmyk"},
    {"xh","Xhosa"},
    {"xmf","Mingrelian"},
    {"xnr","Kangri"},
    {"xog","Soga"},
    {"yao","Yao"},
    {"yap","Yapese"},
    {"yav","Yangben"},
    {"ybb","Yemba"},
    {"yi","Yiddish"},
    {"yo","Yoruba"},
    {"yrl","Nheengatu"},
    {"yue","Cantonese"},
    {"yue-alt-menu","Chinese, Cantonese"},
    {"za","Zhuang"},
    {"zap","Zapotec"},
    {"zbl","Blissymbols"},
    {"zea","Zeelandic"},
    {"zen","Zenaga"},
    {"zgh","Standard Moroccan Tamazight"},
    {"zh","Chinese"},
    {"zh-Hans","Simplified Chinese"},
    {"zh-Hans-alt-long","Simplified Mandarin Chinese"},
    {"zh-Hant","Traditional Chinese"},
    {"zh-Hant-alt-long","Traditional Mandarin Chinese"},
    {"zh-alt-long","Mandarin Chinese"},
    {"zh-alt-menu","Chinese, Mandarin"},
    {"zu","Zulu"},
    {"zun","Zuni"},
    {"zxx","No linguistic content"},
    {"zza","Zaza"},
};



static const std::unordered_map<std::string, std::string> COUNTRY_MAP = {
    {"001","world"},
    {"002","Africa"},
    {"003","North America"},
    {"005","South America"},
    {"009","Oceania"},
    {"011","Western Africa"},
    {"013","Central America"},
    {"014","Eastern Africa"},
    {"015","Northern Africa"},
    {"017","Middle Africa"},
    {"018","Southern Africa"},
    {"019","Americas"},
    {"021","Northern America"},
    {"029","Caribbean"},
    {"030","Eastern Asia"},
    {"034","Southern Asia"},
    {"035","Southeast Asia"},
    {"039","Southern Europe"},
    {"053","Australasia"},
    {"054","Melanesia"},
    {"057","Micronesian Region"},
    {"061","Polynesia"},
    {"142","Asia"},
    {"143","Central Asia"},
    {"145","Western Asia"},
    {"150","Europe"},
    {"151","Eastern Europe"},
    {"154","Northern Europe"},
    {"155","Western Europe"},
    {"202","Sub-Saharan Africa"},
    {"419","Latin America"},
    {"AC","Ascension Island"},
    {"AD","Andorra"},
    {"AE","United Arab Emirates"},
    {"AF","Afghanistan"},
    {"AG","Antigua & Barbuda"},
    {"AI","Anguilla"},
    {"AL","Albania"},
    {"AM","Armenia"},
    {"AO","Angola"},
    {"AQ","Antarctica"},
    {"AR","Argentina"},
    {"AS","American Samoa"},
    {"AT","Austria"},
    {"AU","Australia"},
    {"AW","Aruba"},
    {"AX","Åland Islands"},
    {"AZ","Azerbaijan"},
    {"BA","Bosnia & Herzegovina"},
    {"BA-alt-short","Bosnia"},
    {"BB","Barbados"},
    {"BD","Bangladesh"},
    {"BE","Belgium"},
    {"BF","Burkina Faso"},
    {"BG","Bulgaria"},
    {"BH","Bahrain"},
    {"BI","Burundi"},
    {"BJ","Benin"},
    {"BL","St. Barthélemy"},
    {"BM","Bermuda"},
    {"BN","Brunei"},
    {"BO","Bolivia"},
    {"BQ","Caribbean Netherlands"},
    {"BR","Brazil"},
    {"BS","Bahamas"},
    {"BT","Bhutan"},
    {"BV","Bouvet Island"},
    {"BW","Botswana"},
    {"BY","Belarus"},
    {"BZ","Belize"},
    {"CA","Canada"},
    {"CC","Cocos (Keeling) Islands"},
    {"CC-alt-short","Cocos Islands"},
    {"CD","Congo - Kinshasa"},
    {"CD-alt-variant","Congo (DRC)"},
    {"CF","Central African Republic"},
    {"CG","Congo - Brazzaville"},
    {"CG-alt-variant","Congo (Republic)"},
    {"CH","Switzerland"},
    {"CI","Côte d’Ivoire"},
    {"CI-alt-variant","Ivory Coast"},
    {"CK","Cook Islands"},
    {"CL","Chile"},
    {"CM","Cameroon"},
    {"CN","China"},
    {"CO","Colombia"},
    {"CP","Clipperton Island"},
    {"CQ","Sark"},
    {"CR","Costa Rica"},
    {"CU","Cuba"},
    {"CV","Cape Verde"},
    {"CV-alt-variant","Cabo Verde"},
    {"CW","Curaçao"},
    {"CX","Christmas Island"},
    {"CY","Cyprus"},
    {"CZ","Czechia"},
    {"CZ-alt-variant","Czech Republic"},
    {"DE","Germany"},
    {"DG","Diego Garcia"},
    {"DJ","Djibouti"},
    {"DK","Denmark"},
    {"DM","Dominica"},
    {"DO","Dominican Republic"},
    {"DZ","Algeria"},
    {"EA","Ceuta & Melilla"},
    {"EC","Ecuador"},
    {"EE","Estonia"},
    {"EG","Egypt"},
    {"EH","Western Sahara"},
    {"ER","Eritrea"},
    {"ES","Spain"},
    {"ET","Ethiopia"},
    {"EU","European Union"},
    {"EZ","Eurozone"},
    {"FI","Finland"},
    {"FJ","Fiji"},
    {"FK","Falkland Islands"},
    {"FK-alt-variant","Falkland Islands (Islas Malvinas)"},
    {"FM","Micronesia"},
    {"FO","Faroe Islands"},
    {"FR","France"},
    {"GA","Gabon"},
    {"GB","United Kingdom"},
    {"GB-alt-short","UK"},
    {"GD","Grenada"},
    {"GE","Georgia"},
    {"GF","French Guiana"},
    {"GG","Guernsey"},
    {"GH","Ghana"},
    {"GI","Gibraltar"},
    {"GL","Greenland"},
    {"GM","Gambia"},
    {"GN","Guinea"},
    {"GP","Guadeloupe"},
    {"GQ","Equatorial Guinea"},
    {"GR","Greece"},
    {"GS","South Georgia & South Sandwich Islands"},
    {"GT","Guatemala"},
    {"GU","Guam"},
    {"GW","Guinea-Bissau"},
    {"GY","Guyana"},
    {"HK","Hong Kong SAR China"},
    {"HK-alt-short","Hong Kong"},
    {"HM","Heard & McDonald Islands"},
    {"HN","Honduras"},
    {"HR","Croatia"},
    {"HT","Haiti"},
    {"HU","Hungary"},
    {"IC","Canary Islands"},
    {"ID","Indonesia"},
    {"IE","Ireland"},
    {"IL","Israel"},
    {"IM","Isle of Man"},
    {"IN","India"},
    {"IO","British Indian Ocean Territory"},
    {"IO-alt-chagos","Chagos Archipelago"},
    {"IQ","Iraq"},
    {"IR","Iran"},
    {"IS","Iceland"},
    {"IT","Italy"},
    {"JE","Jersey"},
    {"JM","Jamaica"},
    {"JO","Jordan"},
    {"JP","Japan"},
    {"KE","Kenya"},
    {"KG","Kyrgyzstan"},
    {"KH","Cambodia"},
    {"KI","Kiribati"},
    {"KM","Comoros"},
    {"KN","St. Kitts & Nevis"},
    {"KP","North Korea"},
    {"KR","South Korea"},
    {"KW","Kuwait"},
    {"KY","Cayman Islands"},
    {"KZ","Kazakhstan"},
    {"LA","Laos"},
    {"LB","Lebanon"},
    {"LC","St. Lucia"},
    {"LI","Liechtenstein"},
    {"LK","Sri Lanka"},
    {"LR","Liberia"},
    {"LS","Lesotho"},
    {"LT","Lithuania"},
    {"LU","Luxembourg"},
    {"LV","Latvia"},
    {"LY","Libya"},
    {"MA","Morocco"},
    {"MC","Monaco"},
    {"MD","Moldova"},
    {"ME","Montenegro"},
    {"MF","St. Martin"},
    {"MG","Madagascar"},
    {"MH","Marshall Islands"},
    {"MK","North Macedonia"},
    {"ML","Mali"},
    {"MM","Myanmar (Burma)"},
    {"MM-alt-short","Myanmar"},
    {"MN","Mongolia"},
    {"MO","Macao SAR China"},
    {"MO-alt-short","Macao"},
    {"MP","Northern Mariana Islands"},
    {"MQ","Martinique"},
    {"MR","Mauritania"},
    {"MS","Montserrat"},
    {"MT","Malta"},
    {"MU","Mauritius"},
    {"MV","Maldives"},
    {"MW","Malawi"},
    {"MX","Mexico"},
    {"MY","Malaysia"},
    {"MZ","Mozambique"},
    {"NA","Namibia"},
    {"NC","New Caledonia"},
    {"NE","Niger"},
    {"NF","Norfolk Island"},
    {"NG","Nigeria"},
    {"NI","Nicaragua"},
    {"NL","Netherlands"},
    {"NO","Norway"},
    {"NP","Nepal"},
    {"NR","Nauru"},
    {"NU","Niue"},
    {"NZ","New Zealand"},
    {"NZ-alt-variant","Aotearoa New Zealand"},
    {"OM","Oman"},
    {"PA","Panama"},
    {"PE","Peru"},
    {"PF","French Polynesia"},
    {"PG","Papua New Guinea"},
    {"PH","Philippines"},
    {"PK","Pakistan"},
    {"PL","Poland"},
    {"PM","St. Pierre & Miquelon"},
    {"PN","Pitcairn Islands"},
    {"PN-alt-short","Pitcairn"},
    {"PR","Puerto Rico"},
    {"PS","Palestinian Territories"},
    {"PS-alt-short","Palestine"},
    {"PT","Portugal"},
    {"PW","Palau"},
    {"PY","Paraguay"},
    {"QA","Qatar"},
    {"QO","Outlying Oceania"},
    {"RE","Réunion"},
    {"RO","Romania"},
    {"RS","Serbia"},
    {"RU","Russia"},
    {"RW","Rwanda"},
    {"SA","Saudi Arabia"},
    {"SB","Solomon Islands"},
    {"SC","Seychelles"},
    {"SD","Sudan"},
    {"SE","Sweden"},
    {"SG","Singapore"},
    {"SH","St. Helena"},
    {"SI","Slovenia"},
    {"SJ","Svalbard & Jan Mayen"},
    {"SK","Slovakia"},
    {"SL","Sierra Leone"},
    {"SM","San Marino"},
    {"SN","Senegal"},
    {"SO","Somalia"},
    {"SR","Suriname"},
    {"SS","South Sudan"},
    {"ST","São Tomé & Príncipe"},
    {"SV","El Salvador"},
    {"SX","Sint Maarten"},
    {"SY","Syria"},
    {"SZ","Eswatini"},
    {"SZ-alt-variant","Swaziland"},
    {"TA","Tristan da Cunha"},
    {"TC","Turks & Caicos Islands"},
    {"TD","Chad"},
    {"TF","French Southern Territories"},
    {"TG","Togo"},
    {"TH","Thailand"},
    {"TJ","Tajikistan"},
    {"TK","Tokelau"},
    {"TL","Timor-Leste"},
    {"TL-alt-variant","East Timor"},
    {"TM","Turkmenistan"},
    {"TN","Tunisia"},
    {"TO","Tonga"},
    {"TR","Türkiye"},
    {"TR-alt-variant","Turkey"},
    {"TT","Trinidad & Tobago"},
    {"TV","Tuvalu"},
    {"TW","Taiwan"},
    {"TZ","Tanzania"},
    {"UA","Ukraine"},
    {"UG","Uganda"},
    {"UM","U.S. Outlying Islands"},
    {"UN","United Nations"},
    {"UN-alt-short","UN"},
    {"US","United States"},
    {"US-alt-short","US"},
    {"UY","Uruguay"},
    {"UZ","Uzbekistan"},
    {"VA","Vatican City"},
    {"VC","St. Vincent & Grenadines"},
    {"VE","Venezuela"},
    {"VG","British Virgin Islands"},
    {"VI","U.S. Virgin Islands"},
    {"VN","Vietnam"},
    {"VU","Vanuatu"},
    {"WF","Wallis & Futuna"},
    {"WS","Samoa"},
    {"XA","Pseudo-Accents"},
    {"XB","Pseudo-Bidi"},
    {"XK","Kosovo"},
    {"YE","Yemen"},
    {"YT","Mayotte"},
    {"ZA","South Africa"},
    {"ZM","Zambia"},
    {"ZW","Zimbabwe"},
    {"ZZ","Unknown Region"},
};


static const std::unordered_map<std::string,std::string> GLYPHS_MAP = {
    {"&AElig;", "&#198;"},
    {"&Aacgr;", "&#902;"},
    {"&Aacute;", "&#193;"},
    {"&Abreve;", "&#258;"},
    {"&Acirc;", "&#194;"},
    {"&Acy;", "&#1040;"},
    {"&Agr;", "&#913;"},
    {"&Agrave;", "&#192;"},
    {"&Amacr;", "&#256;"},
    {"&Aogon;", "&#260;"},
    {"&Aring;", "&#197;"},
    {"&Atilde;", "&#195;"},
    {"&Auml;", "&#196;"},
    {"&Barwed;", "&#8892;"},
    {"&Bcy;", "&#1041;"},
    {"&Bgr;", "&#914;"},
    {"&CHcy;", "&#1063;"},
    {"&Cacute;", "&#262;"},
    {"&Cap;", "&#8914;"},
    {"&Ccaron;", "&#268;"},
    {"&Ccedil;", "&#199;"},
    {"&Ccirc;", "&#264;"},
    {"&Cdot;", "&#266;"},
    {"&Cup;", "&#8915;"},
    {"&DJcy;", "&#1026;"},
    {"&DScy;", "&#1029;"},
    {"&DZcy;", "&#1039;"},
    {"&Dagger;", "&#8225;"},
    {"&Dcaron;", "&#270;"},
    {"&Dcy;", "&#1044;"},
    {"&Delta;", "&#916;"},
    {"&Dgr;", "&#916;"},
    {"&Dot;", "&#168;"},
    {"&DotDot;", "&#8412;"},
    {"&Dstrok;", "&#272;"},
    {"&EEacgr;", "&#905;"},
    {"&EEgr;", "&#919;"},
    {"&ENG;", "&#330;"},
    {"&ETH;", "&#208;"},
    {"&Eacgr;", "&#904;"},
    {"&Eacute;", "&#201;"},
    {"&Ecaron;", "&#282;"},
    {"&Ecirc;", "&#202;"},
    {"&Ecy;", "&#1069;"},
    {"&Edot;", "&#278;"},
    {"&Egr;", "&#917;"},
    {"&Egrave;", "&#200;"},
    {"&Emacr;", "&#274;"},
    {"&Eogon;", "&#280;"},
    {"&Euml;", "&#203;"},
    {"&Fcy;", "&#1060;"},
    {"&GJcy;", "&#1027;"},
    {"&Gamma;", "&#915;"},
    {"&Gbreve;", "&#286;"},
    {"&Gcedil;", "&#290;"},
    {"&Gcirc;", "&#284;"},
    {"&Gcy;", "&#1043;"},
    {"&Gdot;", "&#288;"},
    {"&Gg;", "&#8921;"},
    {"&Ggr;", "&#915;"},
    {"&Gt;", "&#8811;"},
    {"&HARDcy;", "&#1066;"},
    {"&Hcirc;", "&#292;"},
    {"&Hstrok;", "&#294;"},
    {"&IEcy;", "&#1045;"},
    {"&IJlig;", "&#306;"},
    {"&IOcy;", "&#1025;"},
    {"&Iacgr;", "&#906;"},
    {"&Iacute;", "&#205;"},
    {"&Icirc;", "&#206;"},
    {"&Icy;", "&#1048;"},
    {"&Idigr;", "&#938;"},
    {"&Idot;", "&#304;"},
    {"&Igr;", "&#921;"},
    {"&Igrave;", "&#204;"},
    {"&Imacr;", "&#298;"},
    {"&Iogon;", "&#302;"},
    {"&Itilde;", "&#296;"},
    {"&Iukcy;", "&#1030;"},
    {"&Iuml;", "&#207;"},
    {"&Jcirc;", "&#308;"},
    {"&Jcy;", "&#1049;"},
    {"&Jsercy;", "&#1032;"},
    {"&Jukcy;", "&#1028;"},
    {"&KHcy;", "&#1061;"},
    {"&KHgr;", "&#935;"},
    {"&KJcy;", "&#1036;"},
    {"&Kcedil;", "&#310;"},
    {"&Kcy;", "&#1050;"},
    {"&Kgr;", "&#922;"},
    {"&LJcy;", "&#1033;"},
    {"&Lacute;", "&#313;"},
    {"&Lambda;", "&#923;"},
    {"&Larr;", "&#8606;"},
    {"&Lcaron;", "&#317;"},
    {"&Lcedil;", "&#315;"},
    {"&Lcy;", "&#1051;"},
    {"&Lgr;", "&#923;"},
    {"&Ll;", "&#8920;"},
    {"&Lmidot;", "&#319;"},
    {"&Lstrok;", "&#321;"},
    {"&Lt;", "&#8810;"},
    {"&Mcy;", "&#1052;"},
    {"&Mgr;", "&#924;"},
    {"&NJcy;", "&#1034;"},
    {"&Nacute;", "&#323;"},
    {"&Ncaron;", "&#327;"},
    {"&Ncedil;", "&#325;"},
    {"&Ncy;", "&#1053;"},
    {"&Ngr;", "&#925;"},
    {"&Ntilde;", "&#209;"},
    {"&OElig;", "&#338;"},
    {"&OHacgr;", "&#911;"},
    {"&OHgr;", "&#937;"},
    {"&Oacgr;", "&#908;"},
    {"&Oacute;", "&#211;"},
    {"&Ocirc;", "&#212;"},
    {"&Ocy;", "&#1054;"},
    {"&Odblac;", "&#336;"},
    {"&Ogr;", "&#927;"},
    {"&Ograve;", "&#210;"},
    {"&Omacr;", "&#332;"},
    {"&Omega;", "&#937;"},
    {"&Oslash;", "&#216;"},
    {"&Otilde;", "&#213;"},
    {"&Ouml;", "&#214;"},
    {"&PHgr;", "&#934;"},
    {"&PSgr;", "&#936;"},
    {"&Pcy;", "&#1055;"},
    {"&Pgr;", "&#928;"},
    {"&Phi;", "&#934;"},
    {"&Pi;", "&#928;"},
    {"&Prime;", "&#8243;"},
    {"&Psi;", "&#936;"},
    {"&Racute;", "&#340;"},
    {"&Rarr;", "&#8608;"},
    {"&Rcaron;", "&#344;"},
    {"&Rcedil;", "&#342;"},
    {"&Rcy;", "&#1056;"},
    {"&Rgr;", "&#929;"},
    {"&SHCHcy;", "&#1065;"},
    {"&SHcy;", "&#1064;"},
    {"&SOFTcy;", "&#1068;"},
    {"&Sacute;", "&#346;"},
    {"&Scaron;", "&#352;"},
    {"&Scedil;", "&#350;"},
    {"&Scirc;", "&#348;"},
    {"&Scy;", "&#1057;"},
    {"&Sgr;", "&#931;"},
    {"&Sigma;", "&#931;"},
    {"&Sub;", "&#8912;"},
    {"&Sup;", "&#8913;"},
    {"&THORN;", "&#222;"},
    {"&THgr;", "&#920;"},
    {"&TSHcy;", "&#1035;"},
    {"&TScy;", "&#1062;"},
    {"&Tcaron;", "&#356;"},
    {"&Tcedil;", "&#354;"},
    {"&Tcy;", "&#1058;"},
    {"&Tgr;", "&#932;"},
    {"&Theta;", "&#920;"},
    {"&Tstrok;", "&#358;"},
    {"&Uacgr;", "&#910;"},
    {"&Uacute;", "&#218;"},
    {"&Ubrcy;", "&#1038;"},
    {"&Ubreve;", "&#364;"},
    {"&Ucirc;", "&#219;"},
    {"&Ucy;", "&#1059;"},
    {"&Udblac;", "&#368;"},
    {"&Udigr;", "&#939;"},
    {"&Ugr;", "&#933;"},
    {"&Ugrave;", "&#217;"},
    {"&Umacr;", "&#362;"},
    {"&Uogon;", "&#370;"},
    {"&Upsi;", "&#978;"},
    {"&Uring;", "&#366;"},
    {"&Utilde;", "&#360;"},
    {"&Uuml;", "&#220;"},
    {"&Vcy;", "&#1042;"},
    {"&Vdash;", "&#8873;"},
    {"&Verbar;", "&#8214;"},
    {"&Vvdash;", "&#8874;"},
    {"&Wcirc;", "&#372;"},
    {"&Xgr;", "&#926;"},
    {"&Xi;", "&#926;"},
    {"&YAcy;", "&#1071;"},
    {"&YIcy;", "&#1031;"},
    {"&YUcy;", "&#1070;"},
    {"&Yacute;", "&#221;"},
    {"&Ycirc;", "&#374;"},
    {"&Ycy;", "&#1067;"},
    {"&Yuml;", "&#376;"},
    {"&ZHcy;", "&#1046;"},
    {"&Zacute;", "&#377;"},
    {"&Zcaron;", "&#381;"},
    {"&Zcy;", "&#1047;"},
    {"&Zdot;", "&#379;"},
    {"&Zgr;", "&#918;"},
    {"&aacgr;", "&#940;"},
    {"&aacute;", "&#225;"},
    {"&abreve;", "&#259;"},
    {"&acirc;", "&#226;"},
    {"&acute;", "&#180;"},
    {"&acy;", "&#1072;"},
    {"&aelig;", "&#230;"},
    {"&agr;", "&#945;"},
    {"&agrave;", "&#224;"},
    {"&aleph;", "&#8501;"},
    {"&alpha;", "&#945;"},
    {"&amacr;", "&#257;"},
    {"&amalg;", "&#8705;"},
    {"&amp;", "&#38;"},
    {"&and;", "&#8743;"},
    {"&ang;", "&#8736;"},
    {"&ang90;", "&#8735;"},
    {"&angmsd;", "&#8737;"},
    {"&angsph;", "&#8738;"},
    {"&angst;", "&#8491;"},
    {"&aogon;", "&#261;"},
    {"&ap;", "&#8776;"},
    {"&ape;", "&#8778;"},
    {"&apos;", "&#39;"},
    {"&aring;", "&#229;"},
    {"&ast;", "&#42;"},
    {"&asymp;", "&#8781;"},
    {"&atilde;", "&#227;"},
    {"&auml;", "&#228;"},
    {"&b.Delta;", "&#916;"},
    {"&b.Gamma;", "&#915;"},
    {"&b.Lambda;", "&#923;"},
    {"&b.Omega;", "&#937;"},
    {"&b.Phi;", "&#934;"},
    {"&b.Pi;", "&#928;"},
    {"&b.Psi;", "&#936;"},
    {"&b.Sigma;", "&#931;"},
    {"&b.Theta;", "&#920;"},
    {"&b.Upsi;", "&#978;"},
    {"&b.Xi;", "&#926;"},
    {"&b.alpha;", "&#945;"},
    {"&b.beta;", "&#946;"},
    {"&b.chi;", "&#967;"},
    {"&b.delta;", "&#948;"},
    {"&b.epsi;", "&#949;"},
    {"&b.epsis;", "&#949;"},
    {"&b.epsiv;", "&#603;"},
    {"&b.eta;", "&#951;"},
    {"&b.gamma;", "&#947;"},
    {"&b.gammad;", "&#988;"},
    {"&b.iota;", "&#953;"},
    {"&b.kappa;", "&#954;"},
    {"&b.kappav;", "&#1008;"},
    {"&b.lambda;", "&#955;"},
    {"&b.mu;", "&#956;"},
    {"&b.nu;", "&#957;"},
    {"&b.omega;", "&#969;"},
    {"&b.phis;", "&#966;"},
    {"&b.phiv;", "&#981;"},
    {"&b.pi;", "&#960;"},
    {"&b.piv;", "&#982;"},
    {"&b.psi;", "&#968;"},
    {"&b.rho;", "&#961;"},
    {"&b.rhov;", "&#1009;"},
    {"&b.sigma;", "&#963;"},
    {"&b.sigmav;", "&#962;"},
    {"&b.tau;", "&#964;"},
    {"&b.thetas;", "&#952;"},
    {"&b.thetav;", "&#977;"},
    {"&b.upsi;", "&#965;"},
    {"&b.xi;", "&#958;"},
    {"&b.zeta;", "&#950;"},
    {"&barwed;", "&#8892;"},
    {"&bcong;", "&#8780;"},
    {"&bcy;", "&#1073;"},
    {"&becaus;", "&#8757;"},
    {"&bepsi;", "&#8717;"},
    {"&bernou;", "&#8492;"},
    {"&beta;", "&#946;"},
    {"&beth;", "&#8502;"},
    {"&bgr;", "&#946;"},
    {"&blank;", "&#9251;"},
    {"&blk12;", "&#9618;"},
    {"&blk14;", "&#9617;"},
    {"&blk34;", "&#9619;"},
    {"&block;", "&#9608;"},
    {"&bottom;", "&#8869;"},
    {"&bowtie;", "&#8904;"},
    {"&boxDL;", "&#9559;"},
    {"&boxDR;", "&#9556;"},
    {"&boxDl;", "&#9558;"},
    {"&boxDr;", "&#9555;"},
    {"&boxH;", "&#9552;"},
    {"&boxHD;", "&#9574;"},
    {"&boxHU;", "&#9577;"},
    {"&boxHd;", "&#9572;"},
    {"&boxHu;", "&#9575;"},
    {"&boxUL;", "&#9565;"},
    {"&boxUR;", "&#9562;"},
    {"&boxUl;", "&#9564;"},
    {"&boxUr;", "&#9561;"},
    {"&boxV;", "&#9553;"},
    {"&boxVH;", "&#9580;"},
    {"&boxVL;", "&#9571;"},
    {"&boxVR;", "&#9568;"},
    {"&boxVh;", "&#9579;"},
    {"&boxVl;", "&#9570;"},
    {"&boxVr;", "&#9567;"},
    {"&boxdL;", "&#9557;"},
    {"&boxdR;", "&#9554;"},
    {"&boxdl;", "&#9488;"},
    {"&boxdr;", "&#9484;"},
    {"&boxh;", "&#9472;"},
    {"&boxhD;", "&#9573;"},
    {"&boxhU;", "&#9576;"},
    {"&boxhd;", "&#9516;"},
    {"&boxhu;", "&#9524;"},
    {"&boxuL;", "&#9563;"},
    {"&boxuR;", "&#9560;"},
    {"&boxul;", "&#9496;"},
    {"&boxur;", "&#9492;"},
    {"&boxv;", "&#9474;"},
    {"&boxvH;", "&#9578;"},
    {"&boxvL;", "&#9569;"},
    {"&boxvR;", "&#9566;"},
    {"&boxvh;", "&#9532;"},
    {"&boxvl;", "&#9508;"},
    {"&boxvr;", "&#9500;"},
    {"&bprime;", "&#8245;"},
    {"&breve;", "&#728;"},
    {"&brvbar;", "&#166;"},
    {"&bsim;", "&#8765;"},
    {"&bsime;", "&#8909;"},
    {"&bsol;", "&#92;"},
    {"&bull;", "&#8226;"},
    {"&bump;", "&#8782;"},
    {"&bumpe;", "&#8783;"},
    {"&cacute;", "&#263;"},
    {"&cap;", "&#8745;"},
    {"&caret;", "&#8257;"},
    {"&caron;", "&#711;"},
    {"&ccaron;", "&#269;"},
    {"&ccedil;", "&#231;"},
    {"&ccirc;", "&#265;"},
    {"&cdot;", "&#267;"},
    {"&cedil;", "&#184;"},
    {"&cent;", "&#162;"},
    {"&chcy;", "&#1095;"},
    {"&check;", "&#10003;"},
    {"&chi;", "&#967;"},
    {"&cir;", "&#9675;"},
    {"&circ;", "&#94;"},
    {"&cire;", "&#8791;"},
    {"&clubs;", "&#9827;"},
    {"&colon;", "&#58;"},
    {"&colone;", "&#8788;"},
    {"&comma;", "&#44;"},
    {"&commat;", "&#64;"},
    {"&comp;", "&#8705;"},
    {"&compfn;", "&#8728;"},
    {"&cong;", "&#8773;"},
    {"&conint;", "&#8750;"},
    {"&coprod;", "&#8720;"},
    {"&copy;", "&#169;"},
    {"&copysr;", "&#8471;"},
    {"&cross;", "&#10007;"},
    {"&cuepr;", "&#8926;"},
    {"&cuesc;", "&#8927;"},
    {"&cularr;", "&#8630;"},
    {"&cup;", "&#8746;"},
    {"&cupre;", "&#8828;"},
    {"&curarr;", "&#8631;"},
    {"&curren;", "&#164;"},
    {"&cuvee;", "&#8910;"},
    {"&cuwed;", "&#8911;"},
    {"&dArr;", "&#8659;"},
    {"&dagger;", "&#8224;"},
    {"&daleth;", "&#8504;"},
    {"&darr;", "&#8595;"},
    {"&darr2;", "&#8650;"},
    {"&dash;", "&#8208;"},
    {"&dashv;", "&#8867;"},
    {"&dblac;", "&#733;"},
    {"&dcaron;", "&#271;"},
    {"&dcy;", "&#1076;"},
    {"&deg;", "&#176;"},
    {"&delta;", "&#948;"},
    {"&dgr;", "&#948;"},
    {"&dharl;", "&#8643;"},
    {"&dharr;", "&#8642;"},
    {"&diam;", "&#8900;"},
    {"&diams;", "&#9830;"},
    {"&die;", "&#168;"},
    {"&divide;", "&#247;"},
    {"&divonx;", "&#8903;"},
    {"&djcy;", "&#1106;"},
    {"&dlarr;", "&#8601;"},
    {"&dlcorn;", "&#8990;"},
    {"&dlcrop;", "&#8973;"},
    {"&dollar;", "&#36;"},
    {"&dot;", "&#729;"},
    {"&drarr;", "&#8600;"},
    {"&drcorn;", "&#8991;"},
    {"&drcrop;", "&#8972;"},
    {"&dscy;", "&#1109;"},
    {"&dstrok;", "&#273;"},
    {"&dtri;", "&#9663;"},
    {"&dtrif;", "&#9662;"},
    {"&dzcy;", "&#1119;"},
    {"&eDot;", "&#8785;"},
    {"&eacgr;", "&#941;"},
    {"&eacute;", "&#233;"},
    {"&ecaron;", "&#283;"},
    {"&ecir;", "&#8790;"},
    {"&ecirc;", "&#234;"},
    {"&ecolon;", "&#8789;"},
    {"&ecy;", "&#1101;"},
    {"&edot;", "&#279;"},
    {"&eeacgr;", "&#942;"},
    {"&eegr;", "&#951;"},
    {"&efDot;", "&#8786;"},
    {"&egr;", "&#949;"},
    {"&egrave;", "&#232;"},
    {"&egs;", "&#8925;"},
    {"&ell;", "&#8467;"},
    {"&els;", "&#8924;"},
    {"&emacr;", "&#275;"},
    {"&empty;", "&#8709;"},
    {"&emsp;", "&#8195;"},
    {"&emsp13;", "&#8196;"},
    {"&emsp14;", "&#8197;"},
    {"&eng;", "&#331;"},
    {"&ensp;", "&#8194;"},
    {"&eogon;", "&#281;"},
    {"&epsi;", "&#949;"},
    {"&epsis;", "&#949;"},
    {"&epsiv;", "&#603;"},
    {"&equals;", "&#61;"},
    {"&equiv;", "&#8801;"},
    {"&erDot;", "&#8787;"},
    {"&esdot;", "&#8784;"},
    {"&eta;", "&#951;"},
    {"&eth;", "&#240;"},
    {"&euml;", "&#235;"},
    {"&excl;", "&#33;"},
    {"&exist;", "&#8707;"},
    {"&fcy;", "&#1092;"},
    {"&female;", "&#9792;"},
    {"&ffilig;", "&#64259;"},
    {"&fflig;", "&#64256;"},
    {"&ffllig;", "&#64260;"},
    {"&filig;", "&#64257;"},
    {"&fjlig;", "&#65533;"},
    {"&flat;", "&#9837;"},
    {"&fllig;", "&#64258;"},
    {"&fnof;", "&#402;"},
    {"&forall;", "&#8704;"},
    {"&fork;", "&#8916;"},
    {"&frac12;", "&#189;"},
    {"&frac13;", "&#8531;"},
    {"&frac14;", "&#188;"},
    {"&frac15;", "&#8533;"},
    {"&frac16;", "&#8537;"},
    {"&frac18;", "&#8539;"},
    {"&frac23;", "&#8532;"},
    {"&frac25;", "&#8534;"},
    {"&frac34;", "&#190;"},
    {"&frac35;", "&#8535;"},
    {"&frac38;", "&#8540;"},
    {"&frac45;", "&#8536;"},
    {"&frac56;", "&#8538;"},
    {"&frac58;", "&#8541;"},
    {"&frac78;", "&#8542;"},
    {"&frown;", "&#8994;"},
    {"&gE;", "&#8807;"},
    {"&gEl;", "&#8923;"},
    {"&gacute;", "&#501;"},
    {"&gamma;", "&#947;"},
    {"&gammad;", "&#988;"},
    {"&gap;", "&#8819;"},
    {"&gbreve;", "&#287;"},
    {"&gcirc;", "&#285;"},
    {"&gcy;", "&#1075;"},
    {"&gdot;", "&#289;"},
    {"&ge;", "&#8805;"},
    {"&gel;", "&#8923;"},
    {"&ges;", "&#8805;"},
    {"&ggr;", "&#947;"},
    {"&gimel;", "&#8503;"},
    {"&gjcy;", "&#1107;"},
    {"&gl;", "&#8823;"},
    {"&gnE;", "&#8809;"},
    {"&gnap;", "&#65533;"},
    {"&gne;", "&#8809;"},
    {"&gnsim;", "&#8935;"},
    {"&grave;", "&#96;"},
    {"&gsdot;", "&#8919;"},
    {"&gsim;", "&#8819;"},
    {"&gt;", "&#62;"},
    {"&gvnE;", "&#8809;"},
    {"&hArr;", "&#8660;"},
    {"&hairsp;", "&#8202;"},
    {"&half;", "&#189;"},
    {"&hamilt;", "&#8459;"},
    {"&hardcy;", "&#1098;"},
    {"&harr;", "&#8596;"},
    {"&harrw;", "&#8621;"},
    {"&hcirc;", "&#293;"},
    {"&hearts;", "&#9825;"},
    {"&hellip;", "&#8230;"},
    {"&horbar;", "&#8213;"},
    {"&hstrok;", "&#295;"},
    {"&hybull;", "&#8259;"},
    {"&hyphen;", "&#45;"},
    {"&iacgr;", "&#943;"},
    {"&iacute;", "&#237;"},
    {"&icirc;", "&#238;"},
    {"&icy;", "&#1080;"},
    {"&idiagr;", "&#912;"},
    {"&idigr;", "&#970;"},
    {"&iecy;", "&#1077;"},
    {"&iexcl;", "&#161;"},
    {"&iff;", "&#8660;"},
    {"&igr;", "&#953;"},
    {"&igrave;", "&#236;"},
    {"&ijlig;", "&#307;"},
    {"&imacr;", "&#299;"},
    {"&image;", "&#8465;"},
    {"&incare;", "&#8453;"},
    {"&infin;", "&#8734;"},
    {"&inodot;", "&#305;"},
    {"&int;", "&#8747;"},
    {"&intcal;", "&#8890;"},
    {"&iocy;", "&#1105;"},
    {"&iogon;", "&#303;"},
    {"&iota;", "&#953;"},
    {"&iquest;", "&#191;"},
    {"&isin;", "&#8712;"},
    {"&itilde;", "&#297;"},
    {"&iukcy;", "&#1110;"},
    {"&iuml;", "&#239;"},
    {"&jcirc;", "&#309;"},
    {"&jcy;", "&#1081;"},
    {"&jnodot;", "&#65533;"},
    {"&jsercy;", "&#1112;"},
    {"&jukcy;", "&#1108;"},
    {"&kappa;", "&#954;"},
    {"&kappav;", "&#1008;"},
    {"&kcedil;", "&#311;"},
    {"&kcy;", "&#1082;"},
    {"&kgr;", "&#954;"},
    {"&kgreen;", "&#312;"},
    {"&khcy;", "&#1093;"},
    {"&khgr;", "&#967;"},
    {"&kjcy;", "&#1116;"},
    {"&lAarr;", "&#8666;"},
    {"&lArr;", "&#8656;"},
    {"&lE;", "&#8806;"},
    {"&lEg;", "&#8922;"},
    {"&lacute;", "&#314;"},
    {"&lagran;", "&#8466;"},
    {"&lambda;", "&#955;"},
    {"&lang;", "&#12296;"},
    {"&lap;", "&#8818;"},
    {"&laquo;", "&#171;"},
    {"&larr;", "&#8592;"},
    {"&larr2;", "&#8647;"},
    {"&larrhk;", "&#8617;"},
    {"&larrlp;", "&#8619;"},
    {"&larrtl;", "&#8610;"},
    {"&lcaron;", "&#318;"},
    {"&lcedil;", "&#316;"},
    {"&lceil;", "&#8968;"},
    {"&lcub;", "&#123;"},
    {"&lcy;", "&#1083;"},
    {"&ldot;", "&#8918;"},
    {"&ldquo;", "&#8220;"},
    {"&ldquor;", "&#8222;"},
    {"&le;", "&#8804;"},
    {"&leg;", "&#8922;"},
    {"&les;", "&#8804;"},
    {"&lfloor;", "&#8970;"},
    {"&lg;", "&#8822;"},
    {"&lgr;", "&#955;"},
    {"&lhard;", "&#8637;"},
    {"&lharu;", "&#8636;"},
    {"&lhblk;", "&#9604;"},
    {"&ljcy;", "&#1113;"},
    {"&lmidot;", "&#320;"},
    {"&lnE;", "&#8808;"},
    {"&lnap;", "&#65533;"},
    {"&lne;", "&#8808;"},
    {"&lnsim;", "&#8934;"},
    {"&lowast;", "&#8727;"},
    {"&lowbar;", "&#95;"},
    {"&loz;", "&#9674;"},
    {"&lozf;", "&#10022;"},
    {"&lpar;", "&#40;"},
    {"&lpargt;", "&#65533;"},
    {"&lrarr2;", "&#8646;"},
    {"&lrhar2;", "&#8651;"},
    {"&lsh;", "&#8624;"},
    {"&lsim;", "&#8818;"},
    {"&lsqb;", "&#91;"},
    {"&lsquo;", "&#8216;"},
    {"&lsquor;", "&#8218;"},
    {"&lstrok;", "&#322;"},
    {"&lt;", "&#60;"},
    {"&lthree;", "&#8907;"},
    {"&ltimes;", "&#8905;"},
    {"&ltri;", "&#9667;"},
    {"&ltrie;", "&#8884;"},
    {"&ltrif;", "&#9666;"},
    {"&lvnE;", "&#8808;"},
    {"&macr;", "&#175;"},
    {"&male;", "&#9794;"},
    {"&malt;", "&#10016;"},
    {"&map;", "&#8614;"},
    {"&marker;", "&#9646;"},
    {"&mcy;", "&#1084;"},
    {"&mdash;", "&#8212;"},
    {"&mgr;", "&#956;"},
    {"&micro;", "&#181;"},
    {"&mid;", "&#8739;"},
    {"&middot;", "&#183;"},
    {"&minus;", "&#8722;"},
    {"&minusb;", "&#8863;"},
    {"&mldr;", "&#8230;"},
    {"&mnplus;", "&#8723;"},
    {"&models;", "&#8871;"},
    {"&mu;", "&#956;"},
    {"&mumap;", "&#8888;"},
    {"&nVDash;", "&#8879;"},
    {"&nVdash;", "&#8878;"},
    {"&nabla;", "&#8711;"},
    {"&nacute;", "&#324;"},
    {"&nap;", "&#8777;"},
    {"&napos;", "&#329;"},
    {"&natur;", "&#9838;"},
    {"&nbsp;", "&#160;"},
    {"&ncaron;", "&#328;"},
    {"&ncedil;", "&#326;"},
    {"&ncong;", "&#8775;"},
    {"&ncy;", "&#1085;"},
    {"&ndash;", "&#8211;"},
    {"&ne;", "&#8800;"},
    {"&nearr;", "&#8599;"},
    {"&nequiv;", "&#8802;"},
    {"&nexist;", "&#8708;"},
    {"&ngE;", "&#8817;"},
    {"&nge;", "&#8817;"},
    {"&nges;", "&#8817;"},
    {"&ngr;", "&#957;"},
    {"&ngt;", "&#8815;"},
    {"&nhArr;", "&#8654;"},
    {"&nharr;", "&#8622;"},
    {"&ni;", "&#8715;"},
    {"&njcy;", "&#1114;"},
    {"&nlArr;", "&#8653;"},
    {"&nlE;", "&#8816;"},
    {"&nlarr;", "&#8602;"},
    {"&nldr;", "&#8229;"},
    {"&nle;", "&#8816;"},
    {"&nles;", "&#8816;"},
    {"&nlt;", "&#8814;"},
    {"&nltri;", "&#8938;"},
    {"&nltrie;", "&#8940;"},
    {"&nmid;", "&#8740;"},
    {"&not;", "&#172;"},
    {"&notin;", "&#8713;"},
    {"&npar;", "&#8742;"},
    {"&npr;", "&#8832;"},
    {"&npre;", "&#8928;"},
    {"&nrArr;", "&#8655;"},
    {"&nrarr;", "&#8603;"},
    {"&nrtri;", "&#8939;"},
    {"&nrtrie;", "&#8941;"},
    {"&nsc;", "&#8833;"},
    {"&nsce;", "&#8929;"},
    {"&nsim;", "&#8769;"},
    {"&nsime;", "&#8772;"},
    {"&nsmid;", "&#65533;"},
    {"&nspar;", "&#8742;"},
    {"&nsub;", "&#8836;"},
    {"&nsubE;", "&#8840;"},
    {"&nsube;", "&#8840;"},
    {"&nsup;", "&#8837;"},
    {"&nsupE;", "&#8841;"},
    {"&nsupe;", "&#8841;"},
    {"&ntilde;", "&#241;"},
    {"&nu;", "&#957;"},
    {"&num;", "&#35;"},
    {"&numero;", "&#8470;"},
    {"&numsp;", "&#8199;"},
    {"&nvDash;", "&#8877;"},
    {"&nvdash;", "&#8876;"},
    {"&nwarr;", "&#8598;"},
    {"&oS;", "&#9416;"},
    {"&oacgr;", "&#972;"},
    {"&oacute;", "&#243;"},
    {"&oast;", "&#8859;"},
    {"&ocir;", "&#8858;"},
    {"&ocirc;", "&#244;"},
    {"&ocy;", "&#1086;"},
    {"&odash;", "&#8861;"},
    {"&odblac;", "&#337;"},
    {"&odot;", "&#8857;"},
    {"&oelig;", "&#339;"},
    {"&ogon;", "&#731;"},
    {"&ogr;", "&#959;"},
    {"&ograve;", "&#242;"},
    {"&ohacgr;", "&#974;"},
    {"&ohgr;", "&#969;"},
    {"&ohm;", "&#8486;"},
    {"&olarr;", "&#8634;"},
    {"&omacr;", "&#333;"},
    {"&omega;", "&#969;"},
    {"&ominus;", "&#8854;"},
    {"&oplus;", "&#8853;"},
    {"&or;", "&#8744;"},
    {"&orarr;", "&#8635;"},
    {"&order;", "&#8500;"},
    {"&ordf;", "&#170;"},
    {"&ordm;", "&#186;"},
    {"&oslash;", "&#248;"},
    {"&osol;", "&#8856;"},
    {"&otilde;", "&#245;"},
    {"&otimes;", "&#8855;"},
    {"&ouml;", "&#246;"},
    {"&par;", "&#8741;"},
    {"&para;", "&#182;"},
    {"&part;", "&#8706;"},
    {"&pcy;", "&#1087;"},
    {"&percnt;", "&#37;"},
    {"&period;", "&#46;"},
    {"&permil;", "&#8240;"},
    {"&perp;", "&#8869;"},
    {"&pgr;", "&#960;"},
    {"&phgr;", "&#966;"},
    {"&phis;", "&#966;"},
    {"&phiv;", "&#981;"},
    {"&phmmat;", "&#8499;"},
    {"&phone;", "&#9742;"},
    {"&pi;", "&#960;"},
    {"&piv;", "&#982;"},
    {"&planck;", "&#295;"},
    {"&plus;", "&#43;"},
    {"&plusb;", "&#8862;"},
    {"&plusdo;", "&#8724;"},
    {"&plusmn;", "&#177;"},
    {"&pound;", "&#163;"},
    {"&pr;", "&#8826;"},
    {"&prap;", "&#8830;"},
    {"&pre;", "&#8828;"},
    {"&prime;", "&#8242;"},
    {"&prnE;", "&#65533;"},
    {"&prnap;", "&#8936;"},
    {"&prnsim;", "&#8936;"},
    {"&prod;", "&#8719;"},
    {"&prop;", "&#8733;"},
    {"&prsim;", "&#8830;"},
    {"&psgr;", "&#968;"},
    {"&psi;", "&#968;"},
    {"&puncsp;", "&#8200;"},
    {"&quest;", "&#63;"},
    {"&quot;", "&#34;"},
    {"&rAarr;", "&#8667;"},
    {"&rArr;", "&#8658;"},
    {"&racute;", "&#341;"},
    {"&radic;", "&#8730;"},
    {"&rang;", "&#12297;"},
    {"&raquo;", "&#187;"},
    {"&rarr;", "&#8594;"},
    {"&rarr2;", "&#8649;"},
    {"&rarrhk;", "&#8618;"},
    {"&rarrlp;", "&#8620;"},
    {"&rarrtl;", "&#8611;"},
    {"&rarrw;", "&#8669;"},
    {"&rcaron;", "&#345;"},
    {"&rcedil;", "&#343;"},
    {"&rceil;", "&#8969;"},
    {"&rcub;", "&#125;"},
    {"&rcy;", "&#1088;"},
    {"&rdquo;", "&#8221;"},
    {"&rdquor;", "&#8221;"},
    {"&real;", "&#8476;"},
    {"&rect;", "&#9645;"},
    {"&reg;", "&#174;"},
    {"&rfloor;", "&#8971;"},
    {"&rgr;", "&#961;"},
    {"&rhard;", "&#8641;"},
    {"&rharu;", "&#8640;"},
    {"&rho;", "&#961;"},
    {"&rhov;", "&#1009;"},
    {"&ring;", "&#730;"},
    {"&rlarr2;", "&#8644;"},
    {"&rlhar2;", "&#8652;"},
    {"&rpar;", "&#41;"},
    {"&rpargt;", "&#65533;"},
    {"&rsh;", "&#8625;"},
    {"&rsqb;", "&#93;"},
    {"&rsquo;", "&#8217;"},
    {"&rsquor;", "&#8217;"},
    {"&rthree;", "&#8908;"},
    {"&rtimes;", "&#8906;"},
    {"&rtri;", "&#9657;"},
    {"&rtrie;", "&#8885;"},
    {"&rtrif;", "&#9656;"},
    {"&rx;", "&#8478;"},
    {"&sacute;", "&#347;"},
    {"&samalg;", "&#8720;"},
    {"&sbsol;", "&#65128;"},
    {"&sc;", "&#8827;"},
    {"&scap;", "&#8831;"},
    {"&scaron;", "&#353;"},
    {"&sccue;", "&#8829;"},
    {"&sce;", "&#8829;"},
    {"&scedil;", "&#351;"},
    {"&scirc;", "&#349;"},
    {"&scnE;", "&#65533;"},
    {"&scnap;", "&#8937;"},
    {"&scnsim;", "&#8937;"},
    {"&scsim;", "&#8831;"},
    {"&scy;", "&#1089;"},
    {"&sdot;", "&#8901;"},
    {"&sdotb;", "&#8865;"},
    {"&sect;", "&#167;"},
    {"&semi;", "&#59;"},
    {"&setmn;", "&#8726;"},
    {"&sext;", "&#10038;"},
    {"&sfgr;", "&#962;"},
    {"&sfrown;", "&#8994;"},
    {"&sgr;", "&#963;"},
    {"&sharp;", "&#9839;"},
    {"&shchcy;", "&#1097;"},
    {"&shcy;", "&#1096;"},
    {"&shy;", "&#173;"},
    {"&sigma;", "&#963;"},
    {"&sigmav;", "&#962;"},
    {"&sim;", "&#8764;"},
    {"&sime;", "&#8771;"},
    {"&smid;", "&#65533;"},
    {"&smile;", "&#8995;"},
    {"&softcy;", "&#1100;"},
    {"&sol;", "&#47;"},
    {"&spades;", "&#9824;"},
    {"&spar;", "&#8741;"},
    {"&sqcap;", "&#8851;"},
    {"&sqcup;", "&#8852;"},
    {"&sqsub;", "&#8847;"},
    {"&sqsube;", "&#8849;"},
    {"&sqsup;", "&#8848;"},
    {"&sqsupe;", "&#8850;"},
    {"&squ;", "&#9633;"},
    {"&square;", "&#9633;"},
    {"&squf;", "&#9642;"},
    {"&ssetmn;", "&#8726;"},
    {"&ssmile;", "&#8995;"},
    {"&sstarf;", "&#8902;"},
    {"&star;", "&#8902;"},
    {"&starf;", "&#9733;"},
    {"&sub;", "&#8834;"},
    {"&subE;", "&#8838;"},
    {"&sube;", "&#8838;"},
    {"&subnE;", "&#8842;"},
    {"&subne;", "&#8842;"},
    {"&sum;", "&#8721;"},
    {"&sup;", "&#8835;"},
    {"&sup1;", "&#185;"},
    {"&sup2;", "&#178;"},
    {"&sup3;", "&#179;"},
    {"&supE;", "&#8839;"},
    {"&supe;", "&#8839;"},
    {"&supnE;", "&#8843;"},
    {"&supne;", "&#8843;"},
    {"&szlig;", "&#223;"},
    {"&target;", "&#8982;"},
    {"&tau;", "&#964;"},
    {"&tcaron;", "&#357;"},
    {"&tcedil;", "&#355;"},
    {"&tcy;", "&#1090;"},
    {"&tdot;", "&#8411;"},
    {"&telrec;", "&#8981;"},
    {"&tgr;", "&#964;"},
    {"&there4;", "&#8756;"},
    {"&thetas;", "&#952;"},
    {"&thetav;", "&#977;"},
    {"&thgr;", "&#952;"},
    {"&thinsp;", "&#8201;"},
    {"&thkap;", "&#8776;"},
    {"&thksim;", "&#8764;"},
    {"&thorn;", "&#254;"},
    {"&tilde;", "&#732;"},
    {"&times;", "&#215;"},
    {"&timesb;", "&#8864;"},
    {"&top;", "&#8868;"},
    {"&tprime;", "&#8244;"},
    {"&trade;", "&#8482;"},
    {"&trie;", "&#8796;"},
    {"&tscy;", "&#1094;"},
    {"&tshcy;", "&#1115;"},
    {"&tstrok;", "&#359;"},
    {"&twixt;", "&#8812;"},
    {"&uArr;", "&#8657;"},
    {"&uacgr;", "&#973;"},
    {"&uacute;", "&#250;"},
    {"&uarr;", "&#8593;"},
    {"&uarr2;", "&#8648;"},
    {"&ubrcy;", "&#1118;"},
    {"&ubreve;", "&#365;"},
    {"&ucirc;", "&#251;"},
    {"&ucy;", "&#1091;"},
    {"&udblac;", "&#369;"},
    {"&udiagr;", "&#944;"},
    {"&udigr;", "&#971;"},
    {"&ugr;", "&#965;"},
    {"&ugrave;", "&#249;"},
    {"&uharl;", "&#8639;"},
    {"&uharr;", "&#8638;"},
    {"&uhblk;", "&#9600;"},
    {"&ulcorn;", "&#8988;"},
    {"&ulcrop;", "&#8975;"},
    {"&umacr;", "&#363;"},
    {"&uml;", "&#168;"},
    {"&uogon;", "&#371;"},
    {"&uplus;", "&#8846;"},
    {"&upsi;", "&#965;"},
    {"&urcorn;", "&#8989;"},
    {"&urcrop;", "&#8974;"},
    {"&uring;", "&#367;"},
    {"&utilde;", "&#361;"},
    {"&utri;", "&#9653;"},
    {"&utrif;", "&#9652;"},
    {"&uuml;", "&#252;"},
    {"&vArr;", "&#8661;"},
    {"&vDash;", "&#8872;"},
    {"&varr;", "&#8597;"},
    {"&vcy;", "&#1074;"},
    {"&vdash;", "&#8866;"},
    {"&veebar;", "&#8891;"},
    {"&vellip;", "&#8942;"},
    {"&verbar;", "&#124;"},
    {"&vltri;", "&#8882;"},
    {"&vprime;", "&#8242;"},
    {"&vprop;", "&#8733;"},
    {"&vrtri;", "&#8883;"},
    {"&vsubnE;", "&#65533;"},
    {"&vsubne;", "&#8842;"},
    {"&vsupnE;", "&#8843;"},
    {"&vsupne;", "&#8843;"},
    {"&wcirc;", "&#373;"},
    {"&wedgeq;", "&#8793;"},
    {"&weierp;", "&#8472;"},
    {"&wreath;", "&#8768;"},
    {"&xcirc;", "&#9711;"},
    {"&xdtri;", "&#9661;"},
    {"&xgr;", "&#958;"},
    {"&xhArr;", "&#8596;"},
    {"&xharr;", "&#8596;"},
    {"&xi;", "&#958;"},
    {"&xlArr;", "&#8656;"},
    {"&xrArr;", "&#8658;"},
    {"&xutri;", "&#9651;"},
    {"&yacute;", "&#253;"},
    {"&yacy;", "&#1103;"},
    {"&ycirc;", "&#375;"},
    {"&ycy;", "&#1099;"},
    {"&yen;", "&#165;"},
    {"&yicy;", "&#1111;"},
    {"&yucy;", "&#1102;"},
    {"&yuml;", "&#255;"},
    {"&zacute;", "&#378;"},
    {"&zcaron;", "&#382;"},
    {"&zcy;", "&#1079;"},
    {"&zdot;", "&#380;"},
    {"&zeta;", "&#950;"},
    {"&zgr;", "&#950;"},
    {"&zhcy;", "&#1078;"},
};



